[mgr]
keymap = [
  { on = "h", run = "leave", desc = "Back to the parent directory" },
  { on = "i", run = "enter", desc = "Enter the child directory" },
  { on = "a", run = "arrow next", desc = "Next file" },
  { on = "e", run = "arrow prev", desc = "Previous file" },
  { on = "q", run = "quit", desc = "Quit the process" },
  { on = "r", run = "rename --cursor=before_ext", desc = "Rename selected file(s)" },
  { on = "o", run = "open", desc = "Open selected files" },
  { on = "O", run = "open --interactive", desc = "Open selected files interactively" },
  { on = "d", run = "remove", desc = "Trash selected files" },
  { on = "D", run = "remove --permanently", desc = "Permanently delete selected files" },
  { on = "t", run = "create", desc = "Create a file (ends with / for directories)" },
  { on = "y", run = "yank", desc = "Yank selected files (copy)" },
  { on = "m", run = "yank --cut", desc = "Yank selected files (cut)" },
  { on = "p", run = "paste", desc = "Paste yanked files" },
  { on = "<Space>", run = ["toggle", "arrow next"], desc = "Toggle the current selection state" },
  { on = "<Esc>", run = "escape", desc = "Exit visual mode, clear selection, or cancel search" },
  { on = "<C-a>", run = "toggle_all --state=on", desc = "Select all files" },
  { on = "<C-r>", run = "toggle_all", desc = "Invert selection of all files" },
  { on = "v", run = "visual_mode", desc = "Enter visual mode (selection mode)" },
  { on = "M", run = "unyank", desc = "Cancel the yank status" },
  { on = "Y", run = "unyank", desc = "Cancel the yank status" },
  { on = "/", run = "find --smart", desc = "Find next file" },
  { on = "?", run = "find --previous --smart", desc = "Find previous file" },
  { on = "n", run = "find_arrow", desc = "Next found" },
  { on = "N", run = "find_arrow --previous", desc = "Previous found" },
  { on = ["g", "g"], run = "arrow top", desc = "Go to top" },
  { on = "G", run = "arrow bot", desc = "Go to bottom" },
  { on = ";", run = "shell --interactive", desc = "Run a shell command" },
  { on = ":", run = "shell --block --interactive", desc = "Run a shell command (block until finishes)" },
  { on = "z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = "Z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
  { on = ["g", "h"], run = "cd ~", desc = "Go home" },
  { on = [",", "b"], run = ["sort btime --reverse=no", "linemode btime"], desc = "Sort by birth time" },
  { on = [",", "B"], run = ["sort btime --reverse=yes", "linemode btime"], desc = "Sort by birth time (reverse)" },
  { on = [",", "m"], run = ["sort mtime --reverse=no", "linemode mtime"], desc = "Sort by modified time" },
  { on = [",", "M"], run = ["sort mtime --reverse=yes", "linemode mtime"], desc = "Sort by modified time (reverse)" },
  { on = "<Tab>", run = "spot", desc = "Spot hovered file" },
  { on = "<Enter>", run = "open", desc = "Open selected files" },
  { on = "<S-Enter>", run = "open --interactive", desc = "Open selected files interactively" },
  { on = [",", "s"], run = ["sort size --reverse=no", "linemode size"], desc = "Sort by size" },
  { on = [",", "S"], run = ["sort size --reverse=yes", "linemode size"], desc = "Sort by size (reverse)" },
  { on = ".", run = "hidden toggle", desc = "Toggle the visibility of hidden files" },
  { on = ["c", "c"], run = "copy path", desc = "Copy the file path" },
  { on = ["c", "d"], run = "copy dirname", desc = "Copy the directory path" },
  { on = ["c", "f"], run = "copy filename", desc = "Copy the filename" },
  { on = ["c", "n"], run = "copy name_without_ext", desc = "Copy the filename without extension" },
  { on = "s", run = "search --via=fd", desc = "Search files by name via fd" },
  { on = "S", run = "search --via=rg", desc = "Search files by content via ripgrep" },
  { on = "<C-s>", run = "escape --search", desc = "Cancel the ongoing search" },
  { on = ["l", "s"], run = "linemode size", desc = "Linemode: size" },
  { on = ["l", "p"], run = "linemode permissions", desc = "Linemode: permissions" },
  { on = ["l", "b"], run = "linemode btime", desc = "Linemode: btime" },
  { on = ["l", "m"], run = "linemode mtime", desc = "Linemode: mtime" },
  { on = ["l", "o"], run = "linemode owner", desc = "Linemode: owner" },
  { on = ["l", "n"], run = "linemode none", desc = "Linemode: none" },
]

[pick]
keymap = [
  { on = "e", run = "arrow prev", desc = "Previous option" },
  { on = "a", run = "arrow next", desc = "Next option" },
  { on = "<Esc>", run = "close", desc = "Cancel pick" },
  { on = "<Enter>", run = "close --submit", desc = "Submit the pick" },
]

[spot]
keymap = [
  { on = "a", run = "arrow next", desc = "Next line" },
  { on = "e", run = "arrow prev", desc = "Previous line" },
  { on = "<Esc>", run = "close", desc = "Close the spot" },
  { on = "~", run = "help", desc = "Open help" },
  { on = ["c", "c"], run = "copy cell", desc = "Copy selected cell" },
]

[input]
keymap = [
  { on = "t", run = "insert", desc = "Enter insert mode" },
  { on = "T", run = ["move first-char", "insert"], desc = "Move to the BOL, and enter insert mode" },
  { on = "s", run = "insert --append", desc = "Enter append mode" },
  { on = "S", run = ["move eol", "insert --append"], desc = "Move to the EOL, and enter append mode" },
  { on = "<Enter>", run = "close --submit", desc = "Submit input" },
  { on = "<Esc>", run = "escape", desc = "Back to normal mode, or cancel input" },
  { on = "<Backspace>", run = "backspace", desc = "Delete the character before the cursor" },
]
